asom.apps.web.inOut/Controllers/FrontEndController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using asom.apps.web.inOut.Controllers.BaseControllers;
using asom.apps.web.inOut.Models.Navigation;

namespace asom.apps.web.inOut.Controllers
{
  public class FrontEndController : BaseController
  {
    // GET: FrontEnd
    public ActionResult Index()
    {
      var setup = WebConfigurationManager.AppSettings["setupInit"];
      if (!string.IsNullOrEmpty(setup))
      {
        if (setup.ToLower() == "false")
        {
          return RedirectToAction("index", "Setup");
        }
      }
      var dbSet = WebConfigurationManager.AppSettings["patchDb"];
      if (!string.IsNullOrEmpty(dbSet))
      {
        if (dbSet.ToLower() == "true")
        {
          return RedirectToAction("PatchDatabase", "Setup");
        }
      }
      ViewBag.SelectedMenu = WebConstants.HOME_MENU;
      ViewBag.PageTitle = "Welcome";
      ViewBag.PageDescription =
        "Get Grants for Business, schools and welfares!!";
      return View();
    }

    public ActionResult Faq()
    {

      ViewBag.SelectedMenu = WebConstants.FAQ;
      ViewBag.PageTitle = "Faq (Frequently Asked Questions)";
      ViewBag.PageDescription = "Financial Help, Crypto Investment, how to make money with bitcoin";
      return View();
    }

 

    public ActionResult Blog()
    {

      ViewBag.SelectedMenu = WebConstants.BLOG;
      return View();
    }
  public ActionResult Contact()
    {

      ViewBag.SelectedMenu = WebConstants.CONTACT;
      return View();
    }
//    [ActionName("terms-and-condition")]
    public ActionResult Terms()
    {
      ViewBag.PageTitle = "Our Terms & Conditions";
      ViewBag.PageDescription = "Terms & conditions, Please read carefully";
      ViewBag.SelectedMenu = WebConstants.ABOUT_MENU;
      return View();
    }


    ActionResult CheckIfSetupIsCompleted()
    {
      var setup = WebConfigurationManager.AppSettings["setupInit"];
      if (!string.IsNullOrEmpty(setup))
      {
        if (setup.ToLower() == "false")
        {
          return RedirectToAction("index", "Setup");
        }
      }
      var dbSet = WebConfigurationManager.AppSettings["patchDb"];
      if (!string.IsNullOrEmpty(dbSet))
      {
        if (dbSet.ToLower() == "true")
        {
          return RedirectToAction("PatchDatabase", "Setup");
        }
      }

      return Content("Hello");
    }
  }
}

asom.apps.web.inOut/Controllers/MenuController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using asom.apps.web.inOut.Controllers.BaseControllers;
using asom.apps.web.inOut.Models.Navigation;

namespace asom.apps.web.inOut.Controllers
{
    public class MenuController : BaseController
    {
        // GET: Menu
        [ActionName("find-submenu")]
       // [OutputCache(Duration = 120,VaryByParam = "id")]
        public ActionResult FindSubMenusOfMainMenu(string id="Dashboard")
        {
            IEnumerable<SubMenuHeader> res = MenuManager.BuildSubMenusFor(id);
            return PartialView("ui/menu/left/_leftMenu",res);
        }
    }
}

asom.apps.web.inOut/Views/Shared/ui/menu/top/_mainMenu.cshtml
@using System.IdentityModel.Metadata
@using asom.apps.inOut.core.model.authentication
@using asom.apps.inOut.core.model.org
@using asom.apps.web.inOut.Controllers.BaseControllers
@using asom.apps.web.inOut.Models
@using asom.apps.web.inOut.Models.Navigation

@*Get Application Menu Here*@
@{
    bool hasOrg  =false;
    bool hasAdminAccess = new IdentityStore().HasAuthority(AppPermissions.CORE_APP_FUNCTIONS_MANAGER);
    IUserIdentity currentUser = IdentitySession.GetOrCreate();
    var companyInfo = OrganizationInfo.Get();
    if (companyInfo != null)
    {
        hasOrg = true;
    }
}

<div class="dashboard-header">
    <nav class="navbar navbar-expand-lg bg-white fixed-top">
        <a class="navbar-brand @hasOrg" href="@Url.Action("Index", "FrontEnd")">Sports Report</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto navbar-right-top">
             
              
              
                <li class="nav-item dropdown nav-user" ng-controller="UserIdentityController">
                    <a class="nav-link nav-user-img" href="" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="card-picture-xxsmall pad10 ">
                            <div class="pic" style="background-image: url(@(currentUser.PictureUrl ?? AppInfo.Get.DefaultAvarter()))" 
                                 ng-style="bgStyle">

                            </div>
                        </div>
                        @*<img src="@currentUser.PictureUrl" alt="" class="user-avatar-md rounded-circle">*@
                    </a>
                    <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                        <div class="nav-user-info">
                            <h5 class="mb-0 text-white nav-user-name">@currentUser.DisplayName </h5>
                          
                            <div class="fade-button" >
                                <asom-file-upload class="btn btn-success btn-xs" ng-show="!uploading"
                                                  file-change="uploadPicture(obj)"
                                                  upload-url="@Url.Action("UploadFileToServer", "Home",
                                                                  new {directoryPath = "user-profile\\passport", allowedExtensions = AllowedExtensionsConstant.IMAGE_FILE_EXTENSION})"
                                                  upload-text="Change Picture"></asom-file-upload>

                            </div>
                            <span class=" " ng-show="uploading">

                                <img src="~/images/ajax-loader.gif" width="90"/>
                            </span>
                        </div>
                        <a class="dropdown-item" ui-sref="settings-state.myprofile-state"><i class="fas fa-user mr-2"></i>Profile</a>
                        @if (hasAdminAccess)
                        {
                           <a class="dropdown-item" ui-sref="settings-state.create-users-state"><i class="fas icon-people mr-2"></i>Admin Users</a> 
                           @*<a class="dropdown-item" ui-sref="settings-state.edit-company-state"><i class="fas fa-briefcase mr-2"></i>Company Profile</a> 
                           <a class="dropdown-item" ui-sref="settings-state.other-settings-state"><i class="fas fa-cog mr-2"></i>Settings</a> *@
                        }
                        
                        <a class="dropdown-item" href="@Url.Action("Logout", "Home")"><i class="fas fa-power-off mr-2"></i>Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>

asom.apps.web.inOut/Views/Shared/ui/menu/top/_mobileMainMenu.cshtml
@using asom.apps.web.inOut.Models
@using asom.apps.web.inOut.Models.Navigation
@*Get Application Menu Here*@
@{
    var appMenus = MenuManager.GetApplicationMainMenu();
    var activeMenu = appMenus.FirstOrDefault(x => x.IsActive == true && x.IsVisible == true);
    bool hasActiveMenu = activeMenu != null;
    string menuUrl = "";
    if (hasActiveMenu)
    {
        menuUrl = @Url.Content("~/ " + activeMenu.Url);
    }
}

<!-- Make this Menu the selected Menu by assigning the 'selected' class-->
 <!-- Make this Menu the selected Menu by assigning the 'selected' class-->






<div class="bg-primary color-white-forced shadow-sm  -stronger-thick-and-heavy" id="mobileMenu">
    <div class="iasom-fixed-left-menu-ui pos-relative">
        <span ng-controller="MenuController" class=" cursor-pointer" style="z-index: 300; position: absolute; right: 0;" ng-click="closeMenu('#mobileMenu')">
          <a href="" class=" btn btn-success btn-md "
                                                 >X</a></span>

        <div class="min-h10 text-center  margin-t-20" ng-controller="UserIdentityController">
            <div class="current-user-box">
                @{

                    string displayName = "";
                    UserIdentityModel id = IdentitySession.GetOrCreate() as UserIdentityModel;
                    try
                    {
                        displayName = id.DisplayName;
                        if (id.DisplayName.Length >= 14)
                        {
                            displayName = id.DisplayName.Split(new String[] {" "}, StringSplitOptions.RemoveEmptyEntries)[0];
                        }
                    }
                    catch
                    {
                        displayName = id.DisplayName;
                        //throw;
                    }
                }
                @Html.Partial("ui/_current_user_avartar", true)
                @if (id != null)
                {
                    <p class="current-user-name font-size-14 margin-t-10">
                        <a href="@Url.Action("Index", "FrontEnd")" title="Goto Home page"><i class="ion-ios-home-outline font-size-17"> </i></a> &nbsp;@displayName <span ng-show="!uploading">(<a href="@Url.Action("Logout", "Home")" class="font-size-13">Log Out <i class="ion-lock-combination"></i></a>)</span>
                    </p>
                }
                else
                {
                    <br/>
                    <a href="@Url.Action("Logout", "Home")" class="font-size-13">Log Out <i class="ion-lock-combination"></i></a>
                }
            </div>

        </div>
        <div class="margin-t-20 action-menu  overflow-auto max-height-550">
            <ul class="list-unstyled">
                @foreach (var mnu in appMenus)
                {

                    if (mnu.IsVisible)
                    {
                        <li class="">
                            <a asom-accordion @((!string.IsNullOrEmpty(mnu.Url) ? "ui-sref=" + @mnu.Url + "" : "")) ui-sref-active="bg-primary shadow-sm  -stronger bold "
                                                                                                     class="pad10 color-white-forced bg-accent-color @(mnu.IsActive ? "active-menu" : null) text-uppercase display-block">
                                @mnu.Name @if (mnu.HasBadge)
                                          {
                                              <sup class="badge bg-red">@mnu.BagdeValue</sup>
                                          }

                            </a>
                            <div class="mobile-menu  ">

                                @Html.Action("find-submenu", "Menu", new { id = mnu.Key })
@*                                using ()*@
@*                                {*@
@*                                    *@
@*                                }*@

                            </div>

                        </li>


                    }



                }
            </ul>

        </div>

    </div>
</div>